<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Mapster" Version="7.4.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Abdm.Calculation.DAL\Abdm.Calculation.DAL.csproj" />
    <ProjectReference Include="..\Abdm.Calculation.Graphics\Abdm.Calculation.Graphics.csproj" />
    <ProjectReference Include="..\Abdm.Calculation.Math\Abdm.Calculation.Maths.csproj" />
    <ProjectReference Include="..\Abdm.Calculation.SteelConcrete\Abdm.Calculation.SteelConcrete.csproj" />
  </ItemGroup>

</Project>
